### ISSUE TITLE
basic test failue

### ISSUE THREAD

**Issue by EmpRamses** [tensorflow/lingvo#106]
This time it may lack some library files

> bazel-out/k8-opt/genfiles/lingvo/core/ops/hyps.pb.cc:11:50: fatal error: google/protobuf/wire_format_lite_inl.h: No such file or directory

**Comment by drpngx** [comment]
Are you running from the docker definition? Same tensorflow version?

**Comment by EmpRamses** [comment]
Yes, it was run from the docker definition. I just follow the docker instruction of the master branch.
Tensorflow version: 1.14.1-dev20190620

**Comment by drpngx** [comment]
Hey, so @jonathanasdf, it looks like the tf version that we're pinned to
uses protobuf 3.7.0. I've looked at the most recent comment in the
tensorflow bzl file, and it says 3.8.0, but it might be wrong.
grep -R "define PROTOBUF_VERSION"
/usr/local/lib/python2.7/site-packages/tensorflow/include/google/protobuf/
gives me 3.7.1. so I think we should pin the protoc to 3.7.1. Not sure if
the tensorflow comment is wrong, or if it's going to 3.8.0. I know there
was a refactoring in issue 19032.

**Comment by drpngx** [comment]
FWIW, I did:

pip2 install pydot2
pip2 uninstall pyparsing
pip2 install pyparsing==1.5.7
perl -wpe 's,v3.8.0/protoc-3.8.0-,v3.7.1/protoc-3.7.1-,;
s/717903f32653f07cd895cfe89ca18ff4ca35f825afa7fe17bcb5cb13bf628be0/24ea6924faaf94d4a0c5850fdb278290a326eff9a68f36ee5809654faccd0e10/'
-i lingvo/lingvo/repo.bzl

and it appears to build. The pyparsing is annoying because it does put a
line that foils our tensorflow autoconf. I thought tail -1 would work but
apparently it does not.

Patrick

**Comment by jonathanasdf** [comment]
Current lingvo HEAD should build with the latest tf-nightly version

https://github.com/tensorflow/tensorflow/blob/dad4197fcf00186df0fe2842228750f484d72b40/tensorflow/workspace.bzl#L379

The update was done in e60d0f20799b42723ae9c70cb82f1808a1190c12 -- do you have that commit?

**Comment by drpngx** [comment]
thank you @jonathanasdf ! @EmpRamses did that work for you?

**Comment by EmpRamses** [comment]
@drpngx It didn't work for mine. But I just changed the ipykernel to ipykernel==4.10.0, and run bagel with --jobs=1. Then it works. I have no idea what happened before. It seems related with ipykernel? Because I added --jobs=1 before and it still failed.
