### ISSUE TITLE
how `is_eval` to propagate to task?

### ISSUE THREAD

**Issue by NiHaoUCAS** [tensorflow/lingvo#109]
In the` trainer.py`, at class Decoder, I see` self.params.is_eval = True`, but how `is_eval` propagate to `self.params.task.is_eval`, and `self.params.task.encoder.is_eval`, `self.params.task.decoder.is_eval`. 
THANK YOU!

**Comment by drpngx** [comment]
@vrv looked into this iirc

It's in the base runner I think

**Comment by vrv** [comment]
https://github.com/tensorflow/lingvo/blob/644841b682009e830f25117ea4b2b71ece5b3126/lingvo/core/base_layer.py#L226 it happens in base_layer.py when you copy the base params from the parent (e.g., during CreateChild).

For is_eval, I think we would recommend instead inspecting cluster_factory.Current().job and checking whether it is the job type you want (evaler, decoder, etc.) instead of using is_eval.

**Comment by NiHaoUCAS** [comment]
> https://github.com/tensorflow/lingvo/blob/644841b682009e830f25117ea4b2b71ece5b3126/lingvo/core/base_layer.py#L226
> 
> it happens in base_layer.py when you copy the base params from the parent (e.g., during CreateChild).
> For is_eval, I think we would recommend instead inspecting cluster_factory.Current().job and checking whether it is the job type you want (evaler, decoder, etc.) instead of using is_eval.

thank you very much, I got it!
