### ISSUE TITLE
Python debugging and Lingvo 

### ISSUE THREAD

**Issue by andrei-n-85** [tensorflow/lingvo#84]
Hi, 

First, thank you for sharing and supporting this project. 
     I am new to working with bazel and docker and have been trying for some time now to include lingvo  with my setup in Pycharm such that I could use the graphical debugger and the line by line execution in order to understand  more about the library and  how to use it in our own projects. 
    For me there is no clear path to achieve such a goal and I would like to ask for your suggestions if this is possible and if not what would you suggest as an alternative for comprehensive debugging 

Thanks a lot for the help!

**Comment by jonathanasdf** [comment]
bazel build should produce a directory structure in which it should be possible to work directly with raw python files. You cannot use the files before bazel build is run because of the c++ and proto dependencies that need to be compiled.

Something like:

```
bazel build -c opt lingvo:trainer
cd bazel-bin/lingvo/trainer.runfiles/__main__/lingvo
```

Note that this is only good for debugging. Any changes to the files in the bazel-bin directories will be overwritten the next time you build, so code changes should be done to the files in the main directory.

**Comment by andrei-n-85** [comment]
Thank you very much, I will give it a try and see what happens.
